# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('NYSE', 'NYSE'), ('AMEX', 'American Stock Exchange'), ('NASDQ', 'Nasdaq')], max_length=5)),
                ('ticker', models.CharField(max_length=45)),
                ('cik', models.CharField(max_length=10)),
                ('underlying', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('O  ', 'Option'), ('L  ', 'Long Position'), ('S  ', 'Short Position'), ('C  ', 'Commodity Position'), ('T  ', 'Tracking Position'), ('W  ', 'Watchlist Item')], default='L  ', max_length=3)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('transactionDate', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
