# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userloginreg', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='userloginreg.User'),
            preserve_default=False,
        ),
    ]
